500 - Server error wenn user schon registriert
makeless/makeless-go pull request #17
Opened 2020-10-10 20:46 UTC by peakle

PR for issue: #10 

PR as part of the Hacktoberfest :)

2020-10-19 15:53 UTC, loeffel-io commented
Thank you very much for your PR - we cant merge any prs currently because there is no license 
Will come back to you soon

2020-12-01 15:10 UTC, loeffel-io commented
Hey @peakle 

License finally added:

- https://github.com/makeless/makeless-go#license
- https://github.com/makeless/makeless-go/blob/master/.github/pull_request_template.md

2020-12-02 18:20 UTC, peakle commented
i fixed conflicts, how to agree with license?

2020-12-04 14:40 UTC, loeffel-io commented
@peakle just paste in this content as comment: https://raw.githubusercontent.com/makeless/makeless-go/master/.github/pull_request_template.md 

after that i will review your pr :-)

2020-12-04 19:11 UTC, peakle commented
# Pull Request template

- [ ] I added a descriptive title & description for my pull request
- [ ] I also created a working demo branch at the [makeless-demo](https://github.com/makeless/makeless-demo) repository: `https://github.com/peakle/makeless-go`
- [ ] I agree the [license](https://github.com/makeless/makeless-go/blob/master/LICENSE)

2020-12-07 13:14 UTC, loeffel-io requested changes

2020-12-07 13:14 UTC, loeffel-io commented on security/error.go
> +	UserAlreadyExist    = errors.New("you are already registred")
Please just change the message to "user already exists"

2020-12-07 13:14 UTC, loeffel-io commented on database/basic/user.go
> +	err := connection.
this file can be discarded - there is no valuable change

2020-12-07 13:14 UTC, loeffel-io commented on security/basic/security.go
> +	exists, err := security.UserExists(connection, "email", *user.Email)
please just move everything to the http handlers (register,registerTeamInvitation) like here: https://github.com/makeless/makeless-go/blob/master/password_request.go#L33

instead of using the switch err style we are now using there `error.is` pattern (since the gorm v2 update) like here: https://github.com/makeless/makeless-go/blob/master/team_invitation.go#L27

2020-12-07 19:52 UTC, peakle commented on database/basic/user.go
> +	err := connection.
but we send `count` var by pointer and update it inside the method `Count`, so when we verify count var before update, it correct?

2020-12-08 00:31 UTC, loeffel-io commented on database/basic/user.go
> +	err := connection.
we put in the count var via reference so the internal code should look like https://play.golang.org/p/FR5BIS92RqU 
imo the count var should be correct

2020-12-09 06:35 UTC, peakle commented
@loeffel-io update by comments

2020-12-09 10:10 UTC, loeffel-io requested changes

2020-12-09 10:10 UTC, loeffel-io commented on register.go
> +	makeless_go_http "github.com/makeless/makeless-go/http"
we can remove the aliases everywhere for `http` + `mailer` + `model` and `security`

2020-12-09 10:10 UTC, loeffel-io commented on team_invitation.go
> +				c.AbortWithStatusJSON(h.StatusOK, http.Response(makeless_go_security.UserAlreadyExists, nil))
200 is the wrong status code - we should just use 400 as you did before

2020-12-09 10:10 UTC, loeffel-io commented
@peakle looks beaufiful, just some optimizations needed

2020-12-09 19:12 UTC, peakle commented
@loeffel-io updated

2020-12-10 08:58 UTC, loeffel-io commented
Thanks @peakle

2020-12-10 08:59 UTC, merged